#ifndef BIAS_BASIC_TYPES_HPP
#define BIAS_BASIC_TYPES_HPP

namespace bias {

    enum CameraLib 
    {
        CAMERA_LIB_FC2=0,
        CAMERA_LIB_DC1394,
        CAMERA_LIB_UNDEFINED,
        NUMBER_OF_CAMERA_LIB,
    };

    enum ErrorCode {

        // Camera library errors
        ERROR_CAMERA_LIB_UNKNOWN=1,
        ERROR_CAMERA_LIB_UNDEFINED,

        // FlyCapture2 specific errors
        ERROR_NO_FC2,
        ERROR_FC2_CREATE_CONTEXT,
        ERROR_FC2_DESTROY_CONTEXT,
        ERROR_FC2_CONNECT,
        ERROR_FC2_DISCONNECT,
        ERROR_FC2_START_CAPTURE,
        ERROR_FC2_STOP_CAPTURE,
        ERROR_FC2_RETRIEVE_BUFFER,
        ERROR_FC2_GRAB_IMAGE,
        ERROR_FC2_CREATE_IMAGE,
        ERROR_FC2_DESTROY_IMAGE,
        ERROR_FC2_GET_GUID,
        ERROR_FC2_ENUMERATE_CAMERAS,
        ERROR_FC2_GET_CAMERA_FROM_INDEX,
        ERROR_FC2_CONVERT_IMAGE,
        ERROR_FC2_GET_FORMAT7_INFO,
        ERROR_FC2_GET_FORMAT7_CONFIGURATION,
        ERROR_FC2_UNSUPPORTED_VIDEO_MODE,
        ERROR_FC2_VALIDATE_FORMAT7_SETTINGS,
        ERROR_FC2_INVALID_FORMAT7_SETTINGS,
        ERROR_FC2_SET_FORMAT7_CONFIGURATION,
        ERROR_FC2_GET_DEFAULT_OUTPUT_FORMAT,
        ERROR_FC2_GET_CAMERA_INFO,
        ERROR_FC2_GET_PROPERTY_INFO,

        ERROR_FC2_CONVERT_PROPERTY_TYPE,
        ERROR_FC2_CONVERT_FRAMERATE,
        ERROR_FC2_CONVERT_VIDEOMODE,
        ERROR_FC2_CONVERT_IMAGING_MODE,

        // Libdc1394 specific errors
        ERROR_NO_DC1394,
        ERROR_DC1394_CREATE_CONTEXT,
        ERROR_DC1394_NULL_POINTER,
        ERROR_DC1394_ENUMERATE_CAMERAS,
        ERROR_DC1394_NEW_CAMERA,
        ERROR_DC1394_SET_VIDEO_MODE,
        ERROR_DC1394_CAPTURE_SETUP,
        ERROR_DC1394_SET_VIDEO_TRANSMISSION,
        ERROR_DC1394_CAPTURE_DEQUEUE,
        ERROR_DC1394_START_CAPTURE,
        ERROR_DC1394_GRAB_IMAGE,

        NUMBER_OF_ERROR,
    }; 
    
    enum PropertyType 
    { 
        PROPERTY_BRIGHTNESS=0, 
        PROPERTY_AUTO_EXPOSURE,
        PROPERTY_SHARPNESS,
        PROPERTY_WHITE_BALANCE,
        PROPERTY_HUE,
        PROPERTY_SATURATION,
        PROPERTY_GAMMA,
        PROPERTY_IRIS,
        PROPERTY_FOCUS,
        PROPERTY_ZOOM,
        PROPERTY_PAN,
        PROPERTY_TILT,
        PROPERTY_SHUTTER,
        PROPERTY_GAIN,
        PROPERTY_TRIGGER_MODE,
        PROPERTY_TRIGGER_DELAY,
        PROPERTY_FRAME_RATE,
        PROPERTY_TEMPERATURE,

        NUMBER_OF_PROPERTY,
    };

    enum FrameRate
    {
        FRAMERATE_1_875=0, 
        FRAMERATE_3_75, 
        FRAMERATE_7_5, 
        FRAMERATE_15, 
        FRAMERATE_30, 
        FRAMERATE_60, 
        FRAMERATE_120, 
        FRAMERATE_240, 
        FRAMERATE_FORMAT7, 

        NUMBER_OF_FRAMERATE,
    };

    enum VideoMode 
    {
        VIDEOMODE_160x120YUV444=0, 
        VIDEOMODE_320x240YUV422, 
        VIDEOMODE_640x480YUV411, 
        VIDEOMODE_640x480YUV422, 
        VIDEOMODE_640x480RGB, 
        VIDEOMODE_640x480Y8, 
        VIDEOMODE_640x480Y16, 
        VIDEOMODE_800x600YUV422, 
        VIDEOMODE_800x600RGB, 
        VIDEOMODE_800x600Y8, 
        VIDEOMODE_800x600Y16, 
        VIDEOMODE_1024x768YUV422, 
        VIDEOMODE_1024x768RGB, 
        VIDEOMODE_1024x768Y8, 
        VIDEOMODE_1024x768Y16, 
        VIDEOMODE_1280x960YUV422, 
        VIDEOMODE_1280x960RGB, 
        VIDEOMODE_1280x960Y8, 
        VIDEOMODE_1280x960Y16, 
        VIDEOMODE_1600x1200YUV422, 
        VIDEOMODE_1600x1200RGB, 
        VIDEOMODE_1600x1200Y8, 
        VIDEOMODE_1600x1200Y16, 
        VIDEOMODE_FORMAT7, 

        NUMBER_OF_VIDEOMODE,
    };

    enum ImagingMode 
    {
        IMAGING_MODE_0=0,
        IMAGING_MODE_1,
        IMAGING_MODE_2,
        IMAGING_MODE_3,
        IMAGING_MODE_4,
        IMAGING_MODE_5,
        IMAGING_MODE_6,
        IMAGING_MODE_7,
        IMAGING_MODE_8,
        IMAGING_MODE_9,
        IMAGING_MODE_10,
        IMAGING_MODE_11,
        IMAGING_MODE_12,
        IMAGING_MODE_13,
        IMAGING_MODE_14,
        IMAGING_MODE_15,
        IMAGING_MODE_16,
        IMAGING_MODE_17,
        IMAGING_MODE_18,
        IMAGING_MODE_19,
        IMAGING_MODE_20,
        IMAGING_MODE_21,
        IMAGING_MODE_22,
        IMAGING_MODE_23,
        IMAGING_MODE_24,
        IMAGING_MODE_25,
        IMAGING_MODE_26,
        IMAGING_MODE_27,
        IMAGING_MODE_28,
        IMAGING_MODE_29,
        IMAGING_MODE_30,
        IMAGING_MODE_31,

        NUMBER_OF_IMAGING_MODE, 
    };  

} // namespace bias

#endif // #ifndef BIAS_BASIC_TYPES_HPP
